apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: void-daemonset
spec:
  selector:
    matchLabels:
      app: void
  template:
    metadata:
      labels:
        app: void
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: void-container
        image: ghcr.io/devnw/void:latest
        ports:
        - containerPort: 53
          protocol: UDP
        volumeMounts:
        - name: void-storage
          mountPath: /etc/void
  volumes:
  - name: void-storage
    hostPath:
      path: /etc/void
      type: DirectoryOrCreate
