apiVersion: apps/v1
kind: Deployment
metadata:
  name: void-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: void
  template:
    metadata:
      labels:
        app: void
    spec:
      containers:
      - name: void-container
        image: ghcr.io/devnw/void:v0.0.10-beta2
        ports:
        - containerPort: 53
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m

---

apiVersion: v1
kind: Service
metadata:
  name: void-loadbalancer
spec:
  selector:
    app: void
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: void-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: void-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
