name: automerge
on:
  pull_request:
    types:
      - labeled
jobs:
  automerge:
    runs-on: nixos
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_LABELS: automerge
