name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build & Unit Tests"
    strategy:
      matrix:
        platform: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19.x
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
